services:
  - type: web
    name: freevst-manager-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false

  - type: static
    name: freevst-manager-frontend
    env: static
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: out
